import type { AuditConfig, InactiveMember, OrgAuditResult, TeamAuditResult } from './types.js';

const ISSUE_BODY_LIMIT = 60_000;

export interface RenderedReport {
	readonly title: string;
	readonly body: string;
	readonly labels: readonly string[];
	readonly truncated: boolean;
}

function escapeCell(s: string): string {
	return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function memberRow(m: InactiveMember): string {
	const teams = m.teams.length > 0 ? m.teams.map((t) => `\`${t}\``).join(', ') : '-';
	const lastSeen = m.lastSeen ?? '-';
	return `| @${escapeCell(m.login)} | ${m.reason} | ${escapeCell(lastSeen)} | ${teams} |`;
}

function errorsBlock(errors: readonly { login: string; cause: string }[]): string {
	if (errors.length === 0) return '';
	const lines = errors.map((e) => `- @${e.login} - \`${e.cause}\``);
	return ['## Errors', ...lines, ''].join('\n');
}

function maybeTruncate(body: string): { body: string; truncated: boolean } {
	if (body.length <= ISSUE_BODY_LIMIT) return { body, truncated: false };
	const head = body.slice(0, ISSUE_BODY_LIMIT - 200);
	return {
		body: `${head}\n\n_…body truncated; see action logs for the full list._`,
		truncated: true,
	};
}

export function renderOrgReport(result: OrgAuditResult, cfg: AuditConfig): RenderedReport {
	const title = `Organization Inactivity Audit - ${result.org}`;
	const summary = [
		`# ${title}`,
		'',
		`_Run: ${result.runAt} · Window: last ${cfg.inactivityDays} days · Inactive: ${result.inactive.length}/${result.totalAudited}_`,
		'',
		'## Summary',
		`- Inactive members: ${result.inactive.length}`,
		`- Members with no team: ${result.noTeamCount}`,
		`- Members with no recent activity: ${result.noActivityCount}`,
		`- Both signals: ${result.bothCount}`,
		'',
	].join('\n');

	const tableHeader =
		'## Inactive members\n\n| Login | Reason | Last seen | Teams |\n|---|---|---|---|';
	const rows =
		result.inactive.length === 0
			? '\n_No inactive members found._'
			: '\n' + result.inactive.map(memberRow).join('\n');

	const errors = errorsBlock(result.errors);
	const footer =
		'\n\n<sub>Generated by organization-auditor. Body is overwritten on each run; comments preserved.</sub>';

	const raw = `${summary}${tableHeader}${rows}\n\n${errors}${footer}`;
	const { body, truncated } = maybeTruncate(raw);

	return {
		title,
		body,
		labels: ['organization-auditor', 'audit:org'],
		truncated,
	};
}

export function renderTeamReport(result: TeamAuditResult, cfg: AuditConfig): RenderedReport {
	const title = `Team Inactivity Audit - ${result.slug}`;
	const repos =
		result.auditedRepos.length > 0
			? result.auditedRepos.map((r) => `\`${r}\``).join(', ')
			: '_(none - team has no auditable repos)_';

	const summary = [
		`# ${title}`,
		'',
		`_Run: ${result.runAt} · Window: last ${cfg.inactivityDays} days · Inactive: ${result.inactive.length}/${result.totalAudited}_`,
		'',
		`Repos audited: ${repos}`,
		'',
	].join('\n');

	const tableHeader =
		'## Inactive members\n\n| Login | Reason | Last seen | Teams |\n|---|---|---|---|';
	const rows =
		result.inactive.length === 0
			? '\n_No inactive members found._'
			: '\n' + result.inactive.map(memberRow).join('\n');

	const errors = errorsBlock(result.errors);
	const footer = '\n\n<sub>Generated by organization-auditor.</sub>';

	const raw = `${summary}${tableHeader}${rows}\n\n${errors}${footer}`;
	const { body, truncated } = maybeTruncate(raw);

	return {
		title,
		body,
		labels: ['organization-auditor', `audit:team:${result.slug}`],
		truncated,
	};
}
